### ISSUE TITLE
수업자료PPT 업로드 요청드립니다.

### ISSUE THREAD

**Issue by hyunsooda** [romandev/chromium101#3]
안녕하세요 8월29일~30일 이틀동안 진행되었던 캠프 참여했던 학생입니다.
강의자료PPT를 업로드해주신다고하셨는데 계속 기다리다 안올라와서 글 올립니다 ㅠㅠ
이틀동안 소중한 강의해주셔서 감사드립니다 :)

**Comment by romandev** [comment]
안녕하세요 현수 학생!

마지막까지 열심히 수업을 들어주셔서 감사합니다.

강의 자료를 아직 Chromium101에 업데이트를 못하였습니다. 주말 내지는 다음주 중으로 업데이트 할 예정인데

일단 이 메일로 다음과 같이 보내드립니다.

[1] Chromium 소개:
https://drive.google.com/open?id=1sB15tlsE1bGwdCOuh_rtaHz-XW5D_4cTXzuaD0dmLU4
[2] Chromium 내부:
https://drive.google.com/open?id=16rGonIRR6S-yBmlJg-uJ-_-4cvaLvJFKxLmv0O2Sd5I

감사합니다!


2018년 9월 1일 오전 2:50, hyunsooda <notifications@github.com>님이 작성:
